name: Terraform Plan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-plan:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Azure Login
        shell: powershell
        run: |
          az account show --output table

      - name: Terraform Version
        shell: powershell
        run: |
          terraform --version

      - name: Terraform Init
        shell: powershell
        run: |
          terraform init

      - name: Terraform Validate
        shell: powershell
        run: |
          terraform validate

      - name: Terraform Plan
        shell: powershell
        run: |
          terraform plan
