permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: "42133458-581f-4d9b-80ce-19b3fca592e9"
  ARM_TENANT_ID: "c8f1af26-7fc1-4c5a-a985-e119d2abba15"
  ARM_SUBSCRIPTION_ID: "33e9da52-73fb-4456-aac2-4547ed5d7ac1"

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Azure Login
    uses: azure/login@v2
    with:
      client-id: ${{ env.ARM_CLIENT_ID }}
      tenant-id: ${{ env.ARM_TENANT_ID }}
      subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

  - name: Verify Azure
    run: |
      az account show

  - name: Terraform Init
    run: terraform init

  - name: Terraform Plan
    run: terraform plan