name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  # -----------------------------
  # Terraform Plan for PR
  # -----------------------------
  terraform-plan-pr:
    if: github.event_name == 'pull_request'
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Azure Login
        shell: powershell
        run: |
          az account show --output table

      - name: Terraform Version
        shell: powershell
        run: |
          terraform --version

      - name: Terraform Init
        shell: powershell
        run: |
          terraform init

      - name: Terraform Validate
        shell: powershell
        run: |
          terraform validate

      - name: Terraform Plan
        shell: powershell
        run: |
          terraform plan


  # -----------------------------
  # Terraform Plan after Merge
  # -----------------------------
  terraform-plan-main:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Azure Login
        shell: powershell
        run: |
          az account show --output table

      - name: Terraform Version
        shell: powershell
        run: |
          terraform --version

      - name: Terraform Init
        shell: powershell
        run: |
          terraform init

      - name: Terraform Validate
        shell: powershell
        run: |
          terraform validate

      - name: Terraform Plan
        shell: powershell
        run: |
          terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan


  # -----------------------------
  # Manual Approval + Apply
  # -----------------------------
  terraform-apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: terraform-plan-main
    runs-on: self-hosted

    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Check Azure Login
        shell: powershell
        run: |
          az account show --output table

      - name: Terraform Init
        shell: powershell
        run: |
          terraform init

      - name: Terraform Apply
        shell: powershell
        run: |
          terraform apply -auto-approve tfplan
